# Generated by Django 3.1.7 on 2021-04-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learner_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aproximatedHours', models.FloatField()),
                ('active', models.BooleanField()),
                ('learners', models.ManyToManyField(to='learner_app.learner')),
            ],
            options={
                'verbose_name': 'capability',
                'verbose_name_plural': 'capabilities',
            },
        ),
        migrations.CreateModel(
            name='capability_objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.capability')),
            ],
            options={
                'verbose_name': 'capability_objective',
                'verbose_name_plural': 'capability_objective',
            },
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('capability_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.capability_objective')),
            ],
        ),
        migrations.CreateModel(
            name='dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('co', 'content'), ('ob', 'objective'), ('gl', 'global')], max_length=2)),
                ('referenceId', models.IntegerField()),
                ('leftPending', models.BooleanField()),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.capability')),
            ],
        ),
        migrations.CreateModel(
            name='objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='training_technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('types', models.CharField(choices=[('txt', 'text'), ('img', 'image'), ('vid', 'video'), ('doc', 'document'), ('game', 'game')], max_length=4)),
                ('reference', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.content')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField()),
                ('mark', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.exercise')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner_app.learner_profile')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.dimension'),
        ),
        migrations.AddField(
            model_name='capability_objective',
            name='objective',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='common_app.objective'),
        ),
        migrations.CreateModel(
            name='capability_learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.capability')),
                ('last_content_done', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common_app.content')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner_app.learner_profile')),
            ],
        ),
        migrations.AddField(
            model_name='capability',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.organization'),
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('isCorrect', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.dimension')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.objective')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.phase')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
            },
        ),
    ]
