# Generated by Django 3.1.7 on 2021-04-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='common_app.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer_profile',
            name='organizations',
            field=models.ManyToManyField(to='common_app.organization'),
        ),
    ]
