# Generated by Django 3.1.7 on 2021-04-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_app', '0001_initial'),
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='trainer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trainer_app.trainer_profile'),
        ),
    ]
