# Generated by Django 3.1.7 on 2021-05-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='active',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='aproximatedHours',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='capability',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='objectives',
            field=models.ManyToManyField(blank=True, default=None, null=True, through='common_app.capability_objective', to='common_app.objective'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.organization'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='common_app.stakeholders'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='trainer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.trainer_profile'),
        ),
    ]
