# Generated by Django 3.1.7 on 2021-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_auto_20210503_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
