# Generated by Django 3.1.7 on 2021-04-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_capability_trainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='answers',
            new_name='answer',
        ),
        migrations.AlterModelOptions(
            name='capability_learner',
            options={'verbose_name': 'capability_learner', 'verbose_name_plural': 'capability_learner'},
        ),
    ]
