# Generated by Django 3.1.7 on 2021-05-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0003_auto_20210503_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='trainer_app/img/capabilities'),
        ),
    ]
