# Generated by Django 3.1.7 on 2021-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0003_auto_20210421_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='description',
            field=models.TextField(default='With out description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capability',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
