# Generated by Django 3.1.7 on 2021-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0003_auto_20210419_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
