# Generated by Django 3.1.7 on 2021-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0004_auto_20210504_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='objectives',
            field=models.ManyToManyField(default=None, through='common_app.capability_objective', to='common_app.objective'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='stakeholders',
            field=models.ManyToManyField(default=None, to='common_app.stakeholders'),
        ),
    ]
