# Generated by Django 3.1.7 on 2021-04-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0004_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='objective',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.objective'),
        ),
    ]
