# Generated by Django 3.1.7 on 2021-04-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_auto_20210422_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholders',
            options={'verbose_name': 'stakeholders', 'verbose_name_plural': 'stakeholders'},
        ),
    ]
