# Generated by Django 3.1.7 on 2021-05-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_auto_20210505_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='capability_objective',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.capability_objective'),
        ),
        migrations.AlterField(
            model_name='content',
            name='dimension',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.dimension'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
