# Generated by Django 3.1.7 on 2021-04-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_auto_20210419_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.objective'),
        ),
    ]
