# Generated by Django 3.1.7 on 2021-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0006_auto_20210510_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='image_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='link_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='text_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='training_technique',
            name='reference',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training_technique',
            name='types',
            field=models.CharField(choices=[('txt', 'Text'), ('img', 'Image'), ('vid', 'Video'), ('doc', 'Document'), ('link', 'Link'), ('game', 'Game')], max_length=4),
        ),
    ]
