# Generated by Django 3.1.7 on 2021-04-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0006_auto_20210422_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_profile',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.stakeholders'),
        ),
    ]
