# Generated by Django 3.1.7 on 2021-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0007_auto_20210422_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_profile',
            name='rol',
            field=models.CharField(max_length=20),
        ),
    ]
