# Generated by Django 3.1.7 on 2021-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0007_auto_20210512_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='video_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='file_component',
            new_name='document_component',
        ),
    ]
