# Generated by Django 3.1.7 on 2021-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0008_auto_20210512_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_technique',
            name='types',
            field=models.CharField(choices=[('txt', 'Text'), ('img', 'Image'), ('vid', 'Video'), ('doc', 'Document'), ('lnk', 'Link'), ('gme', 'Game')], max_length=4),
        ),
    ]
