# Generated by Django 3.1.7 on 2021-04-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0009_auto_20210422_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='activities',
            field=models.ManyToManyField(related_name='objectives', to='common_app.activity'),
        ),
    ]
