# Generated by Django 3.1.7 on 2021-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0010_auto_20210426_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='activities',
            field=models.ManyToManyField(to='common_app.activity'),
        ),
    ]
