# Generated by Django 3.1.7 on 2021-05-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0011_auto_20210512_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game_component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image_component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='link_component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='text_component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='training_technique',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='training_technique',
            name='types',
        ),
        migrations.RemoveField(
            model_name='video_component',
            name='id',
        ),
        migrations.AddField(
            model_name='document_component',
            name='training_technique_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_app.training_technique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_component',
            name='training_technique_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_app.training_technique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image_component',
            name='training_technique_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_app.training_technique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link_component',
            name='training_technique_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_app.training_technique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text_component',
            name='training_technique_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_app.training_technique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video_component',
            name='training_technique_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_app.training_technique'),
            preserve_default=False,
        ),
    ]
