# Generated by Django 3.1.7 on 2021-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0014_auto_20210520_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='scope',
            field=models.CharField(choices=[('co', 'content'), ('ob', 'objective'), ('ca', 'ca')], max_length=2),
        ),
    ]
