# Generated by Django 3.1.7 on 2021-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0017_auto_20210526_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='isCorrect',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
