# Generated by Django 3.1.7 on 2021-05-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0019_auto_20210526_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capability',
            old_name='aproximatedHours',
            new_name='aproximatedTime',
        ),
    ]
