# Generated by Django 3.1.7 on 2021-06-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0021_auto_20210601_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_profile',
            name='imagen',
            field=models.ImageField(blank=True, default='static/unknown_profile.png', null=True, upload_to='img/users'),
        ),
        migrations.AlterField(
            model_name='trainer_profile',
            name='imagen',
            field=models.ImageField(blank=True, default='static/unknown_profile.png', null=True, upload_to='img/users'),
        ),
    ]
