# Generated by Django 3.1.7 on 2021-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0022_auto_20210601_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_profile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
