# Generated by Django 3.1.7 on 2021-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0024_trainer_profile_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_profile',
            name='actual_organization_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
