# Generated by Django 3.1.7 on 2021-06-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0026_auto_20210602_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner_profile',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='trainer_profile',
            old_name='imagen',
            new_name='image',
        ),
    ]
