# Generated by Django 3.1.7 on 2021-06-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0027_auto_20210602_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability_learner',
            name='capability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.capability'),
        ),
        migrations.AlterField(
            model_name='capability_learner',
            name='last_content_done',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='capability_learner',
            name='learner_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.learner_profile'),
        ),
    ]
