# Generated by Django 3.1.7 on 2021-06-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0030_auto_20210607_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='exercise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.exercise'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='learner_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.learner_profile'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='mark',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
