# Generated by Django 3.1.7 on 2021-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0031_auto_20210609_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability_learner',
            name='pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
