# Generated by Django 3.1.7 on 2021-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0032_capability_learner_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='capabilities'),
        ),
        migrations.AlterField(
            model_name='document_component',
            name='value',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contents/doc'),
        ),
        migrations.AlterField(
            model_name='image_component',
            name='value',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='contents/img'),
        ),
        migrations.AlterField(
            model_name='learner_profile',
            name='image',
            field=models.ImageField(blank=True, default='static/unknown_profile.png', null=True, upload_to='users/profile_image'),
        ),
        migrations.AlterField(
            model_name='trainer_profile',
            name='image',
            field=models.ImageField(blank=True, default='static/unknown_profile.png', null=True, upload_to='users/profile_image'),
        ),
        migrations.AlterField(
            model_name='video_component',
            name='value',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contents/video'),
        ),
    ]
