# Generated by Django 3.1.7 on 2021-06-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0036_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.organization'),
        ),
    ]
