# Generated by Django 3.1.7 on 2021-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0038_auto_20210624_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='activities',
            field=models.ManyToManyField(default=None, to='common_app.activity'),
        ),
    ]
