# Generated by Django 3.1.7 on 2021-04-19 18:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learner_app', '0002_auto_20210419_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learner_profile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='learner_profile',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='learner_profile',
            name='user',
        ),
        migrations.AddField(
            model_name='learner_profile',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
