# Generated by Django 3.1.7 on 2021-04-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner_app', '0003_auto_20210419_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learner_profile',
            options={'verbose_name': 'learner_profile', 'verbose_name_plural': 'learner_profiles'},
        ),
    ]
